### PR TITLE
[FIX] Improve long character slot selection lists

### PR DESCRIPTION
**Pull request by Angela-BC**
See #689 

For now I did only adjust DeviceSlotsMenu. Are there other context menu's that needs adjustment?

This change has impact on **all** context menu's, since it sets the max-height in the context-menu css class. Is this going to be an issue?

### CODE REVIEW

**Review by Jomshir98 — CHANGES_REQUESTED** [review]
Hi!
The changes in the context menu break the styling - the character buttons (given sufficiently long slot name, such as those of "Bondage Frame") are no longer stretched and no longer have spacing between them.
I experimented slightly and I suggest more generic fix that will add a scrollbar to _any_ contextmenu, if it gets too big:
- Keep the `max-height` style
- Wrap the content of the device context menu in `<Scrollable>` and `<Column>` so the tree looks like in the code below. This should apply to the following components:
  - `DeviceContextMenuCurrent`
  - `CharacterContextMenu`
  - `ContextMenuImpl`
- Together with that the added `<div>` should be removed from the `DeviceSlotsMenu`.

The code to produce scrollbar for the whole menu while keeping styling intact:
```tsx
<div className='context-menu' ... >
	<Scrollable color='lighter'>
		<Column>
			{ original content }
		</Column>
	</Scrollable>
</div>
```

**Comment by Angela-BC** [comment]
That gets overlooked when the test characters have names like Angela, Dummy, Dummy two, Dummy Three and Dummy four. Looks Like I'd better get some test chars with a longer name.

I adjusted the code as suggested.

**Review by Jomshir98 — APPROVED** [review]
Looks good! Thank you~

**Review by ClaudiaMia — APPROVED** [review]
Tested and working great!~

**Pull request merged**
